export const EXERCICIOS_BASE = [
  {
    nome: "Supino reto",
    grupoMuscular: "Peito",
    gruposSecundarios: ["Tríceps", "Ombros"],
    categoria: "Musculação",
    equipamento: "Barra ou máquina",
    nivel: "Intermediário",
    objetivo: ["Hipertrofia", "Força"],
    padraoSeries: 4,
    padraoRepeticoes: "8-12",
    padraoDescanso: "60-90s",
    instrucoes: "Manter escápulas retraídas, controlar a descida e empurrar sem perder a estabilidade.",
    cuidados: "Evitar excesso de carga sem amplitude segura.",
    status: "Ativo"
  },
  {
    nome: "Puxada frontal",
    grupoMuscular: "Costas",
    gruposSecundarios: ["Bíceps"],
    categoria: "Musculação",
    equipamento: "Pulley",
    nivel: "Iniciante",
    objetivo: ["Hipertrofia", "Condicionamento"],
    padraoSeries: 3,
    padraoRepeticoes: "10-12",
    padraoDescanso: "60s",
    instrucoes: "Puxar a barra em direção ao peito, mantendo tronco estável.",
    cuidados: "Não puxar atrás da nuca.",
    status: "Ativo"
  },
  {
    nome: "Agachamento livre",
    grupoMuscular: "Pernas",
    gruposSecundarios: ["Glúteos", "Core"],
    categoria: "Musculação",
    equipamento: "Peso livre",
    nivel: "Intermediário",
    objetivo: ["Hipertrofia", "Força", "Funcional"],
    padraoSeries: 4,
    padraoRepeticoes: "8-12",
    padraoDescanso: "90s",
    instrucoes: "Descer com controle, mantendo coluna neutra e joelhos alinhados.",
    cuidados: "Avaliar mobilidade e técnica antes de usar carga alta.",
    status: "Ativo"
  },
  {
    nome: "Leg press",
    grupoMuscular: "Pernas",
    gruposSecundarios: ["Glúteos"],
    categoria: "Musculação",
    equipamento: "Leg press",
    nivel: "Iniciante",
    objetivo: ["Hipertrofia", "Condicionamento"],
    padraoSeries: 3,
    padraoRepeticoes: "12",
    padraoDescanso: "60s",
    instrucoes: "Controlar a descida e empurrar a plataforma sem travar os joelhos.",
    cuidados: "Não flexionar demais a lombar.",
    status: "Ativo"
  },
  {
    nome: "Remada baixa",
    grupoMuscular: "Costas",
    gruposSecundarios: ["Bíceps"],
    categoria: "Musculação",
    equipamento: "Cabo",
    nivel: "Iniciante",
    objetivo: ["Hipertrofia", "Postura"],
    padraoSeries: 3,
    padraoRepeticoes: "10-12",
    padraoDescanso: "60s",
    instrucoes: "Puxar mantendo ombros baixos e coluna neutra.",
    cuidados: "Evitar impulso do tronco.",
    status: "Ativo"
  },
  {
    nome: "Desenvolvimento com halteres",
    grupoMuscular: "Ombros",
    gruposSecundarios: ["Tríceps"],
    categoria: "Musculação",
    equipamento: "Halteres",
    nivel: "Intermediário",
    objetivo: ["Hipertrofia"],
    padraoSeries: 3,
    padraoRepeticoes: "10",
    padraoDescanso: "60s",
    instrucoes: "Empurrar os halteres acima da cabeça com controle.",
    cuidados: "Evitar compensação lombar.",
    status: "Ativo"
  },
  {
    nome: "Rosca direta",
    grupoMuscular: "Bíceps",
    gruposSecundarios: [],
    categoria: "Musculação",
    equipamento: "Barra ou halteres",
    nivel: "Iniciante",
    objetivo: ["Hipertrofia"],
    padraoSeries: 3,
    padraoRepeticoes: "10-12",
    padraoDescanso: "45-60s",
    instrucoes: "Flexionar cotovelos sem balançar o tronco.",
    cuidados: "Manter punhos alinhados.",
    status: "Ativo"
  },
  {
    nome: "Tríceps pulley",
    grupoMuscular: "Tríceps",
    gruposSecundarios: [],
    categoria: "Musculação",
    equipamento: "Cabo",
    nivel: "Iniciante",
    objetivo: ["Hipertrofia"],
    padraoSeries: 3,
    padraoRepeticoes: "10-12",
    padraoDescanso: "45-60s",
    instrucoes: "Estender cotovelos mantendo braços próximos ao corpo.",
    cuidados: "Evitar mover os ombros.",
    status: "Ativo"
  },
  {
    nome: "Prancha abdominal",
    grupoMuscular: "Core",
    gruposSecundarios: ["Abdômen"],
    categoria: "Funcional",
    equipamento: "Solo",
    nivel: "Iniciante",
    objetivo: ["Core", "Estabilidade"],
    padraoSeries: 3,
    padraoRepeticoes: "30-45s",
    padraoDescanso: "30s",
    instrucoes: "Manter corpo alinhado, contraindo abdômen e glúteos.",
    cuidados: "Evitar queda do quadril.",
    status: "Ativo"
  },
  {
    nome: "Burpee adaptado",
    grupoMuscular: "Geral",
    gruposSecundarios: ["Cardio"],
    categoria: "Funcional",
    equipamento: "Solo",
    nivel: "Intermediário",
    objetivo: ["Condicionamento", "Emagrecimento"],
    padraoSeries: 3,
    padraoRepeticoes: "10",
    padraoDescanso: "45s",
    instrucoes: "Executar o movimento em ritmo controlado, adaptando impacto conforme nível.",
    cuidados: "Evitar impacto em alunos com dor articular.",
    status: "Ativo"
  },
  {
    nome: "Esteira",
    grupoMuscular: "Cardio",
    gruposSecundarios: ["Pernas"],
    categoria: "Cardio",
    equipamento: "Esteira",
    nivel: "Iniciante",
    objetivo: ["Emagrecimento", "Condicionamento"],
    padraoSeries: 1,
    padraoRepeticoes: "15-30 min",
    padraoDescanso: "-",
    instrucoes: "Controlar intensidade conforme frequência cardíaca e objetivo.",
    cuidados: "Atenção a tonturas, dor ou falta de ar.",
    status: "Ativo"
  },
  {
    nome: "Bike ergométrica",
    grupoMuscular: "Cardio",
    gruposSecundarios: ["Pernas"],
    categoria: "Cardio",
    equipamento: "Bike",
    nivel: "Iniciante",
    objetivo: ["Emagrecimento", "Condicionamento"],
    padraoSeries: 1,
    padraoRepeticoes: "15-30 min",
    padraoDescanso: "-",
    instrucoes: "Ajustar banco e manter cadência confortável.",
    cuidados: "Evitar sobrecarga no joelho.",
    status: "Ativo"
  }
];
