-- JÁ APLICADA NO SUPABASE Fusion ERP.
-- Migration: protect_provisional_tenant_onboarding
--
-- A criação de tenant agora grava:
-- settings.onboarding_status = "pending"
--
-- RPCs instaladas:
-- public.fusion_complete_tenant_onboarding_v1(text,text)
-- public.fusion_cancel_provisional_tenant_v1(text,text)
--
-- A RPC de cancelamento:
-- - bloqueia academia-piloto;
-- - aceita somente onboarding_status = pending;
-- - valida o administrador;
-- - executa toda a exclusão dentro de uma transação PostgreSQL;
-- - remove login, registros V3/V4, recuperação, Access Bridge, Edge e suporte;
-- - remove o tenant somente no fim.
--
-- Não execute este arquivo novamente. Ele é documentação da alteração aplicada.
