/* SQL Manager 2005 Lite for InterBase/Firebird 4.4.0.5                         */
/* ---------------------------------------------------------------------------- */
/* Host     : localhost                                                         */
/* Database : C:\henry.fdb */


CREATE DATABASE 'c:\henry.fdb'   USER 'SYSDBA'
   PASSWORD 'masterkey'
   PAGE_SIZE 4096;


/* Definition for the `HE00_AT_COD_GEN` generator :  */

CREATE GENERATOR HE00_AT_COD_GEN;

/* Definition for the `HE01_AT_COD_GEN` generator :  */

CREATE GENERATOR HE01_AT_COD_GEN;

/* Definition for the `HE02_AT_COD_GEN` generator :  */

CREATE GENERATOR HE02_AT_COD_GEN;

/* Definition for the `HE03_AT_COD_GEN` generator :  */

CREATE GENERATOR HE03_AT_COD_GEN;

/* Definition for the `HE04_AT_COD_GEN` generator :  */

CREATE GENERATOR HE04_AT_COD_GEN;

/* Definition for the `HE05_AT_COD_GEN` generator :  */

CREATE GENERATOR HE05_AT_COD_GEN;

/* Definition for the `HE06_AT_COD_GEN` generator :  */

CREATE GENERATOR HE06_AT_COD_GEN;

/* Definition for the `HE07_AT_COD_GEN` generator :  */

CREATE GENERATOR HE07_AT_COD_GEN;

/* Definition for the `HE08_AT_COD_GEN` generator :  */

CREATE GENERATOR HE08_AT_COD_GEN;

/* Definition for the `HE09_AT_COD_GEN` generator :  */

CREATE GENERATOR HE09_AT_COD_GEN;

/* Definition for the `HE10_AT_COD_GEN` generator :  */

CREATE GENERATOR HE10_AT_COD_GEN;

/* Definition for the `HE11_AT_COD_GEN` generator :  */

CREATE GENERATOR HE11_AT_COD_GEN;

/* Definition for the `HE12_AT_COD_GEN` generator :  */

CREATE GENERATOR HE12_AT_COD_GEN;

/* Definition for the `HE13_AT_COD_GEN` generator :  */

CREATE GENERATOR HE13_AT_COD_GEN;

/* Definition for the `HE14_AT_COD_GEN` generator :  */

CREATE GENERATOR HE14_AT_COD_GEN;

/* Definition for the `HE14_NR_EQUIP_GEN` generator :  */

CREATE GENERATOR HE14_NR_EQUIP_GEN;

/* Definition for the `HE15_AT_COD_GEN` generator :  */

CREATE GENERATOR HE15_AT_COD_GEN;

/* Definition for the `HE16_AT_COD_GEN` generator :  */

CREATE GENERATOR HE16_AT_COD_GEN;

/* Definition for the `HE17_AT_COD_GEN` generator :  */

CREATE GENERATOR HE17_AT_COD_GEN;

/* Definition for the `HE18_AT_COD_GEN` generator :  */

CREATE GENERATOR HE18_AT_COD_GEN;

/* Definition for the `HE19_AT_COD_GEN` generator :  */

CREATE GENERATOR HE19_AT_COD_GEN;

/* Definition for the `HE20_AT_COD_GEN` generator :  */

CREATE GENERATOR HE20_AT_COD_GEN;

/* Definition for the `HE21_AT_COD_GEN` generator :  */

CREATE GENERATOR HE21_AT_COD_GEN;

/* Definition for the `HE22_AT_COD_GEN` generator :  */

CREATE GENERATOR HE22_AT_COD_GEN;

/* Definition for the `HE23_AT_COD_GEN` generator :  */

CREATE GENERATOR HE23_AT_COD_GEN;

/* Definition for the `HE23_AT_COD_GEN` generator :  */

CREATE GENERATOR HE25_AT_COD_GEN;

/* Definition for the `HE27_AT_COD_GEN` generator :  */

CREATE GENERATOR HE27_AT_COD_GEN;

/* Definition for the `HE30_AT_COD_GEN` generator :  */

CREATE GENERATOR HE30_AT_COD_GEN;

/* Definition for the `HE31_AT_COD_GEN` generator :  */

CREATE GENERATOR HE31_AT_COD_GEN;

/* Definition for the `HE33_AT_COD_GEN` generator :  */

CREATE GENERATOR HE33_AT_COD_GEN;

/* Definition for the `HE34_AT_COD_GEN` generator :  */

CREATE GENERATOR HE34_AT_COD_GEN;

/* Definition for the `HE35_AT_COD_GEN` generator :  */

CREATE GENERATOR HE35_AT_COD_GEN;

/* Definition for the `HE36_AT_COD_GEN` generator :  */

CREATE GENERATOR HE36_AT_COD_GEN;

/* Definition for the `HE37_AT_COD_GEN` generator :  */

CREATE GENERATOR HE37_AT_COD_GEN

/* Definition for the `HE39_AT_COD_GEN` generator :  */

CREATE GENERATOR HE39_AT_COD_GEN;



/* Definition for the `COMMENT` domain :  */

CREATE DOMAIN "COMMENT" AS
  BLOB SUB_TYPE 1 CHARACTER SET UNICODE_FSS
  COLLATE UNICODE_FSS;

/* Definition for the `GID` domain :  */

CREATE DOMAIN GID AS
  INTEGER;

/* Definition for the `HOST_KEY` domain :  */

CREATE DOMAIN HOST_KEY AS
  CHAR(20) CHARACTER SET OCTETS
  COLLATE OCTETS;

/* Definition for the `HOST_NAME` domain :  */

CREATE DOMAIN HOST_NAME AS
  CHAR(20) CHARACTER SET ASCII
  COLLATE ASCII;

/* Definition for the `NAME_PART` domain :  */

CREATE DOMAIN NAME_PART AS
  VARCHAR(32) CHARACTER SET UNICODE_FSS
  DEFAULT _UNICODE_FSS ''
  COLLATE UNICODE_FSS;

/* Definition for the `PASSWD` domain :  */

CREATE DOMAIN PASSWD AS
  VARCHAR(32) CHARACTER SET OCTETS
  COLLATE OCTETS;

/* Definition for the `PRIVILEGE` domain :  */

CREATE DOMAIN PRIVILEGE AS
  INTEGER;

/* Definition for the `UID` domain :  */

CREATE DOMAIN UID AS
  INTEGER;

/* Definition for the `USER_NAME` domain :  */

CREATE DOMAIN USER_NAME AS
  VARCHAR(128) CHARACTER SET ASCII
  COLLATE ASCII;


/* Structure for the `HE00` table :  */

CREATE TABLE HE00 (
  HE00_AT_COD INTEGER NOT NULL,
  HE00_BL_GRAVABANCO INTEGER DEFAULT 1 NOT NULL,
  HE00_BL_GRAVATXT INTEGER DEFAULT 1 NOT NULL,
  HE00_NR_TEMPODISPLAY INTEGER DEFAULT 5 NOT NULL,
  HE00_BL_SERVERDATETIME INTEGER DEFAULT 1 NOT NULL,
  HE00_BL_SHOWBATIDA INTEGER DEFAULT 0 NOT NULL,
  HE00_BL_PASSREQUIRED INTEGER DEFAULT 0 NOT NULL,
  HE00_ST_PASSWORD VARCHAR(10) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE00_ST_SECRETPERG VARCHAR(40) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE00_ST_SECRETRESP VARCHAR(40) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE00_FL_LIBERACAOGIRO INTEGER DEFAULT 0 NOT NULL,
  HE00_FL_VIEWLISTA INTEGER DEFAULT 0 NOT NULL,
  HE00_BL_ADVANCEDMODE INTEGER DEFAULT 0 NOT NULL,
  HE00_BL_LARGEICONS INTEGER DEFAULT 1 NOT NULL,
  HE00_BL_AUTOCADASTRO INTEGER DEFAULT 1 NOT NULL,
  HE00_FL_UPDATEMODE INTEGER DEFAULT 0 NOT NULL,
  HE00_BL_HELP INTEGER DEFAULT 1 NOT NULL,
  HE00_BL_FIRSTHIDE INTEGER DEFAULT 1 NOT NULL,
  HE00_BL_PLAYSOUND SMALLINT DEFAULT 1 NOT NULL,
  HE00_FL_ONDETECTOFF SMALLINT DEFAULT 1 NOT NULL,
  HE00_BL_SINCRONIZAR SMALLINT DEFAULT 1 NOT NULL,
  HE00_FL_HAMSTER SMALLINT DEFAULT 2 NOT NULL,
  HE00_ST_IDIOMA VARCHAR(30) CHARACTER SET WIN1252 DEFAULT 'Portugues_Brasil.hlg' NOT NULL COLLATE WIN1252,
  HE00_ST_MSGUP VARCHAR(16) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE00_ST_MSGDOWN VARCHAR(16) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE00_FL_MSGUP_STYLE SMALLINT DEFAULT 0 NOT NULL,
  HE00_FL_MSGDOWN_STYLE SMALLINT DEFAULT 2 NOT NULL,
  HE00_NR_VERSAO INTEGER DEFAULT 7010 NOT NULL,
  HE00_BL_SHOWID INTEGER DEFAULT 0 NOT NULL,
  HE00_NR_NIVELSECBIO INTEGER DEFAULT 4 NOT NULL,
  HE00_HR_APB TIME,
  HE00_NR_SEARCHTIMEOUT INTEGER DEFAULT 0 NOT NULL,
  HE00_BL_ONLINEFREE SMALLINT DEFAULT 1 NOT NULL,
  HE00_BL_APBMODOENTSAI INTEGER DEFAULT 0 NOT NULL,
  HE00_NR_BIOQUALIDADE INTEGER DEFAULT 70 NOT NULL);
	
	
ALTER TABLE HE00 ADD PRIMARY KEY (HE00_AT_COD);



/* Structure for the `HE01` table :  */

CREATE TABLE HE01 (
  HE01_AT_COD INTEGER NOT NULL,
  HE01_NR_MODO INTEGER DEFAULT 0 NOT NULL,
  HE01_BL_CONFIRMADO INTEGER DEFAULT 0 NOT NULL,
  HE01_NR_NUM INTEGER DEFAULT 0 NOT NULL,
  HE01_ST_DESC VARCHAR(30) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE01_NR_CONFIG INTEGER DEFAULT 0 NOT NULL,
  HE01_NR_CONFIGDSP INTEGER DEFAULT 0 NOT NULL,
  HE01_NR_FORMATO INTEGER DEFAULT 0 NOT NULL,
  HE01_NR_MSGPADRAO INTEGER DEFAULT 0 NOT NULL,
  HE01_NR_TIPOCOM INTEGER DEFAULT 0 NOT NULL,
  HE01_ST_PORTA VARCHAR(8) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE01_NR_VELOCIDADE INTEGER DEFAULT 0 NOT NULL,
  HE01_NR_FIRMWARE INTEGER DEFAULT 7000 NOT NULL,
  HE01_FL_PRIORITY INTEGER DEFAULT 2 NOT NULL,
  HE01_ST_MAC VARCHAR(20) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252,
  HE01_NR_MODELO INTEGER DEFAULT -1 NOT NULL,
  HE01_BL_CONECTADO SMALLINT DEFAULT 1 NOT NULL,
  HE01_NR_TCPPORT INTEGER DEFAULT 3000 NOT NULL,
  HE01_ST_IP VARCHAR(20) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE01_ST_FONE VARCHAR(30) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE01_BL_ORION INTEGER DEFAULT 0 NOT NULL,
  HE01_BL_ICMP INTEGER DEFAULT 1 NOT NULL,
	HE01_BL_ATIVO SMALLINT DEFAULT 1 NOT NULL);


ALTER TABLE HE01 ADD PRIMARY KEY (HE01_AT_COD);



/* Structure for the `HE02` table :  */

CREATE TABLE HE02 (
  HE02_AT_COD INTEGER NOT NULL,
  HE02_ST_MATRICULA VARCHAR(20) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE02_ST_MATRICULA_DESCRIPTO VARCHAR(20) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE02_ST_NOME VARCHAR(52) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE02_BL_DENTRO INTEGER DEFAULT 0,
  HE02_NR_EMPRESA INTEGER DEFAULT 0,
  HE02_FL_TPUSER INTEGER DEFAULT 0,
  HE02_NR_HORARIO INTEGER DEFAULT 0,
  HE02_FL_ACESSO INTEGER DEFAULT 0,
  HE02_DT_DENTRO TIMESTAMP,
  HE02_BL_VERIFDIG INTEGER DEFAULT 1 NOT NULL,
  HE02_ST_ACIONARELES VARCHAR(3) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE02_DT_BLOQINI DATE,
  HE02_DT_BLOQEND DATE,
  HE02_BL_BLOQENABLED SMALLINT DEFAULT 0 NOT NULL,
  HE02_ST_CTRLS VARCHAR(10) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
	HE02_ST_PIS VARCHAR(12) CHARACTER SET WIN1252 DEFAULT '' COLLATE WIN1252);
  	

ALTER TABLE HE02 ADD PRIMARY KEY (HE02_AT_COD);



/* Structure for the `HE03` table :  */

CREATE TABLE HE03 (
  HE03_AT_COD INTEGER NOT NULL,
  HE03_NR_FUNCOES INTEGER DEFAULT 0 NOT NULL,
  HE03_NR_FERIADOS INTEGER DEFAULT 0 NOT NULL,
  HE03_NR_ACIONAMENTOS INTEGER DEFAULT 0 NOT NULL,
  HE03_NR_LISTA INTEGER DEFAULT 0 NOT NULL,
  HE03_NR_TABPER INTEGER DEFAULT 0 NOT NULL,
  HE03_NR_TABHOR INTEGER DEFAULT 0 NOT NULL,
  HE03_NR_MSGESP INTEGER DEFAULT 0 NOT NULL,
  HE03_NR_REGISTROS INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE03 ADD PRIMARY KEY (HE03_AT_COD);



/* Structure for the `HE04` table :  */

CREATE TABLE HE04 (
  HE04_AT_COD INTEGER NOT NULL,
  HE04_ST_EMPRESA VARCHAR(150) CHARACTER SET WIN1252 DEFAULT '' COLLATE PXW_INTL850,
  HE04_ST_NUMERO VARCHAR(6) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
	HE04_ST_DOCUMENTO VARCHAR(18) DEFAULT '',
	HE04_ST_CEI VARCHAR(12) DEFAULT '',
	HE04_NR_TIPODOC INTEGER DEFAULT 0);
					  
ALTER TABLE HE04 ADD PRIMARY KEY (HE04_AT_COD);



/* Structure for the `HE05` table :  */

CREATE TABLE HE05 (
  HE05_AT_COD INTEGER NOT NULL,
  HE05_ST_DESC VARCHAR(30) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE05_DT_FERIADO DATE NOT NULL);


ALTER TABLE HE05 ADD PRIMARY KEY (HE05_AT_COD);



/* Structure for the `HE06` table :  */

CREATE TABLE HE06 (
  HE06_AT_COD INTEGER NOT NULL,
  HE06_NR_SEC_LEVEL INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_SEC_LEVEL_IDENT INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_REG_QUAL INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_VER_QUAL INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_HIGH_SEC INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_SMART_CAP INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_BRIGHTNESS INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_GAIN INTEGER DEFAULT 0 NOT NULL,
  HE06_NR_IMG_QUALITY SMALLINT DEFAULT 1 NOT NULL,
  HE06_NR_SEC_FASTMODE SMALLINT DEFAULT 1 NOT NULL,
  HE06_NR_SENSITIVITY SMALLINT DEFAULT 1 NOT NULL,
  HE06_NR_LIGHTING_CONDITION SMALLINT DEFAULT 1 NOT NULL);


ALTER TABLE HE06 ADD PRIMARY KEY (HE06_AT_COD);



/* Structure for the `HE07` table :  */

CREATE TABLE HE07 (
  HE07_AT_COD INTEGER DEFAULT 1 NOT NULL,
  HE07_NR_EMPRESA INTEGER DEFAULT 0 NOT NULL,
  HE07_NR_EQUIPAMENTO INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE07 ADD PRIMARY KEY (HE07_AT_COD);



/* Structure for the `HE08` table :  */

CREATE TABLE HE08 (
  HE08_AT_COD INTEGER DEFAULT 1 NOT NULL,
  HE08_ST_DESCRICAO VARCHAR(20) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252);



/* Structure for the `HE09` table :  */

CREATE TABLE HE09 (
  HE09_AT_COD INTEGER NOT NULL,
  HE09_NR_HORARIO INTEGER DEFAULT 0 NOT NULL,
  HE09_NR_PERIODO INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE09 ADD PRIMARY KEY (HE09_AT_COD);



/* Structure for the `HE10` table :  */

CREATE TABLE HE10 (
  HE10_AT_COD INTEGER NOT NULL,
  HE10_NR_USER INTEGER DEFAULT 0 NOT NULL,
  HE10_NR_EQUIP INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE10 ADD PRIMARY KEY (HE10_AT_COD);



/* Structure for the `HE11` table :  */

CREATE TABLE HE11 (
  HE11_AT_COD INTEGER NOT NULL,
  HE11_ST_DESCHOR VARCHAR(30) CHARACTER SET WIN1252 COLLATE PXW_INTL850);


ALTER TABLE HE11 ADD PRIMARY KEY (HE11_AT_COD);



/* Structure for the `HE12` table :  */

CREATE TABLE HE12 (
  HE12_AT_COD INTEGER NOT NULL,
  HE12_NR_EQUIP INTEGER DEFAULT 0 NOT NULL,
  HE12_BL_ACTIVE INTEGER DEFAULT 0 NOT NULL,
  HE12_BL_LIBACESSO INTEGER DEFAULT 0 NOT NULL,
  HE12_ST_MSG VARCHAR(16) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE12_NR_TEMPO INTEGER DEFAULT 0 NOT NULL,
  HE12_FL_ATALHO INTEGER DEFAULT 0 NOT NULL,
  HE12_BL_ISFNCESPEC SMALLINT DEFAULT 0 NOT NULL);


ALTER TABLE HE12 ADD PRIMARY KEY (HE12_AT_COD);



/* Structure for the `HE13` table :  */

CREATE TABLE HE13 (
  HE13_AT_COD INTEGER NOT NULL,
  HE13_NR_EQUIP INTEGER DEFAULT 0 NOT NULL,
  HE13_NR_DIAS INTEGER DEFAULT 0 NOT NULL,
  HE13_NR_TEMPO INTEGER DEFAULT 0 NOT NULL,
  HE13_HR_HORARIO TIME NOT NULL);


ALTER TABLE HE13 ADD PRIMARY KEY (HE13_AT_COD);



/* Structure for the `HE14` table :  */

CREATE TABLE HE14 (
  HE14_AT_COD INTEGER NOT NULL,
  HE14_NR_EQUIP INTEGER DEFAULT 0 NOT NULL,
  HE14_NR_LAYOUT INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE14 ADD PRIMARY KEY (HE14_AT_COD);



/* Structure for the `HE15` table :  */

CREATE TABLE HE15 (
  HE15_AT_COD INTEGER NOT NULL,
  HE15_HR_HORINI TIME NOT NULL,
  HE15_HR_HOREND TIME NOT NULL,
  HE15_ST_DIAS VARCHAR(8) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252);


ALTER TABLE HE15 ADD PRIMARY KEY (HE15_AT_COD);



/* Structure for the `HE16` table :  */

CREATE TABLE HE16 (
  HE16_AT_COD INTEGER NOT NULL,
  HE16_ST_P_MSG VARCHAR(32) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE16_ST_E_MSG VARCHAR(32) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE16_ST_S_MSG VARCHAR(32) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE16_NR_P_DUR INTEGER DEFAULT 0 NOT NULL,
  HE16_NR_E_DUR INTEGER DEFAULT 0 NOT NULL,
  HE16_NR_S_DUR INTEGER DEFAULT 0 NOT NULL,
  HE16_FL_P_STATUS INTEGER DEFAULT 2 NOT NULL,
  HE16_FL_E_STATUS INTEGER DEFAULT 1 NOT NULL,
  HE16_FL_S_STATUS INTEGER DEFAULT 1 NOT NULL);


ALTER TABLE HE16 ADD PRIMARY KEY (HE16_AT_COD);



/* Structure for the `HE17` table :  */

CREATE TABLE HE17 (
  HE17_AT_COD INTEGER,
  HE17_ST_DESCRICAO VARCHAR(30) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE17_ST_LOCAL VARCHAR(250) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE17_ST_LAYOUT VARCHAR(250) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE17_ST_FUNCOES VARCHAR(400) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE17_FL_TIPOS INTEGER DEFAULT 0 NOT NULL,
  HE17_BL_SECINC INTEGER DEFAULT 0 NOT NULL,
  HE17_BL_READONLY SMALLINT DEFAULT 0 NOT NULL,
  HE17_BL_NAOGIROU INTEGER DEFAULT 0 NOT NULL,
  HE17_BL_FUNCAOEXCLUSIVE SMALLINT DEFAULT 0 NOT NULL);



/* Structure for the `HE18` table :  */

CREATE TABLE HE18 (
  HE18_AT_COD INTEGER NOT NULL,
  HE18_NR_EQUIP INTEGER DEFAULT 0 NOT NULL,
  HE18_NR_MSGESPEC INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE18 ADD PRIMARY KEY (HE18_AT_COD);



/* Structure for the `HE19` table :  */

CREATE TABLE HE19 (
  HE19_AT_COD INTEGER NOT NULL,
  HE19_FL_STATUS INTEGER DEFAULT 0 NOT NULL,
  HE19_ST_MENSAGEM VARCHAR(32) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE19_NR_DURACAO INTEGER DEFAULT 0 NOT NULL,
  HE19_DT_MENSAGEM DATE NOT NULL,
  HE19_BL_ALLDAY SMALLINT DEFAULT 0 NOT NULL);


ALTER TABLE HE19 ADD PRIMARY KEY (HE19_AT_COD);



/* Structure for the `HE20` table :  */

CREATE TABLE HE20 (
  HE20_AT_COD INTEGER NOT NULL,
  HE20_NR_MSGESPEC INTEGER DEFAULT 0 NOT NULL,
  HE20_NR_FUNC INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE20 ADD PRIMARY KEY (HE20_AT_COD);



/* Structure for the `HE21` table :  */

CREATE TABLE HE21 (
  HE21_AT_COD INTEGER NOT NULL,
  HE21_BL_EXPANSION INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_ORIGEM INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_TECLADO INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_RELE1_STATUS INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_RELE1_NANF INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_RELE1_TEMPO INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_RELE2_STATUS INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_RELE2_NANF INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_RELE2_TEMPO INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_RELE3_STATUS INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_RELE3_NANF INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_RELE3_TEMPO INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_LEITOR1 INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_LEITOR2 INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_LEITOR3 INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_NIVELACESSO INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_CTRLACESSO INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_CTRLFLAG_GRAV INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRLFLAG_ATIVAMASTER INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRLFLAG_PASSREQUIRED INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRLFLAG_SINALIZA50PER INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRLFLAG_CATRACA INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRLFLAG_CATRACAINV INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_TOQUESATEND INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_BARCODE_PADRAOD INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_BARCODE_PADRAOT INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_BARCODE_LETRAS INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_BARCODE_PADRAOLIVRE INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_BARCODE_DIGITOSAUTO INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_NUMDIGITOS INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_REVISTA_TIPO INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_REVISTA_PERC INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_SENHA INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_EMPRESA0 VARCHAR(6) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE21_NR_EMPRESA1 VARCHAR(6) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE21_NR_EMPRESA2 VARCHAR(6) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE21_NR_EMPRESA3 VARCHAR(6) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE21_NR_EMPRESA4 VARCHAR(6) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE21_NR_BIOMETRIA INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_HIDESEL SMALLINT DEFAULT 0 NOT NULL,
  HE21_ST_DIGSEL VARCHAR(72) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE21_BL_APB INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_APBMODOENTSAI INTEGER DEFAULT 0 NOT NULL,
  HE21_NR_APBTEMPO INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_ANTIPASSBACK INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRL_SERVER_MATCH SMALLINT DEFAULT 0 NOT NULL,
  HE21_BL_CTRL_TRATABLOQUEIO SMALLINT DEFAULT 0 NOT NULL,
  HE21_BL_FUNCS_ESPEC SMALLINT DEFAULT 0 NOT NULL,
  HE21_BL_CTRL_CATBIOLIBAMBOS SMALLINT DEFAULT 0 NOT NULL,
  HE21_FL_RELE4_STATUS SMALLINT DEFAULT 0 NOT NULL,
  HE21_FL_RELE4_NANF SMALLINT DEFAULT 0 NOT NULL,
  HE21_NR_RELE4_TEMPO INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_RELE5_STATUS SMALLINT DEFAULT 0 NOT NULL,
  HE21_FL_RELE5_NANF SMALLINT DEFAULT 0 NOT NULL,
  HE21_NR_RELE5_TEMPO INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRLFLAG_CATRACADUPLA INTEGER DEFAULT 0 NOT NULL,
  HE21_ST_SENSOR1 VARCHAR(50) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE21_ST_SENSOR2 VARCHAR(50) CHARACTER SET WIN1252 COLLATE WIN1252,
  HE21_BL_CTRL_VISITANTE INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRL_TOUCH INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_CTRL_AUTOON INTEGER DEFAULT 0 NOT NULL,
  HE21_FL_AUTOOFF INTEGER DEFAULT 0 NOT NULL,
  HE21_ST_CTRLS VARCHAR(10) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE21_BL_DIGITAIS11 INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_LEITORNOTVERIFDIG INTEGER DEFAULT 0 NOT NULL,
  HE21_BL_FAIXA SMALLINT DEFAULT 0 NOT NULL,
  HE21_NR_RESET SMALLINT DEFAULT 0 NOT NULL,
  HE21_ST_LOCAL VARCHAR(100) DEFAULT CHARACTER SET WIN1252 DEFAULT '' COLLATE WIN1252),
	HE21_NR_PROC_ONLINE_TIMEOUT SMALLINT DEFAULT 3 NOT NULL,
	HE21_NR_LATENCIA_OFFLINE SMALLINT DEFAULT 5 NOT NULL,
	HE21_BL_MANUAL_CFG SMALLINT DEFAULT 0 NOT NULL;


ALTER TABLE HE21 ADD PRIMARY KEY (HE21_AT_COD);



/* Structure for the `HE22` table :  */

CREATE TABLE HE22 (
  HE22_AT_COD INTEGER NOT NULL,
  HE22_NR_EQUIP INTEGER DEFAULT 0 NOT NULL,
  HE22_ST_MATRICULA VARCHAR(30) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
  HE22_BL_SAIDA INTEGER DEFAULT 0 NOT NULL,
  HE22_BL_LIBMASTER INTEGER DEFAULT 0 NOT NULL,
  HE22_BL_LIBFUNCAO INTEGER DEFAULT 0 NOT NULL,
  HE22_FL_FONTEENT INTEGER DEFAULT 0 NOT NULL,
  HE22_BL_ACESSONEG INTEGER DEFAULT 0 NOT NULL,
  HE22_FL_TIPONEG INTEGER DEFAULT 0 NOT NULL,
  HE22_NR_FUNCAO INTEGER DEFAULT 0 NOT NULL,
  HE22_BL_GIROU INTEGER DEFAULT 0 NOT NULL,
  HE22_DT_REGISTRO TIMESTAMP NOT NULL,
  HE22_BL_ISCATRACA INTEGER DEFAULT 0 NOT NULL,
  HE22_BL_EXPORTADO INTEGER DEFAULT 0 NOT NULL,
  HE22_NR_FLAG INTEGER DEFAULT 0 NOT NULL,
  HE22_NR_CONTROLADOR INTEGER DEFAULT 0 NOT NULL,
  HE22_FL_ORDEM INTEGER DEFAULT 0 NOT NULL);


ALTER TABLE HE22 ADD PRIMARY KEY (HE22_AT_COD);



/* Structure for the `HE23` table :  */

CREATE TABLE HE23 (
  HE23_AT_COD INTEGER NOT NULL,
  HE23_ST_MATRICULA VARCHAR(20) CHARACTER SET WIN1252 NOT NULL COLLATE WIN1252,
  HE23_FL_BIOMETRIA INTEGER DEFAULT 0 NOT NULL,
  HE23_BL_ALFAA INTEGER DEFAULT 1 NOT NULL,
  HE23_BL_MASTER INTEGER DEFAULT 0 NOT NULL,
  HE23_BN_TEMPLATE BLOB SUB_TYPE 2 NOT NULL,
  HE23_DT_LASTEDIT TIMESTAMP NOT NULL);


ALTER TABLE HE23 ADD PRIMARY KEY (HE23_AT_COD);



/* Structure for the `HE24` table :  */

CREATE TABLE HE24 (
  HE24_NR_ESCALA INTEGER DEFAULT 0 NOT NULL,
  HE24_DT_DIA DATE NOT NULL,
  HE24_NR_HORARIO INTEGER DEFAULT 0 NOT NULL);



/* Structure for the `HE25` table :  */

CREATE TABLE HE25 (
  HE25_AT_COD INTEGER NOT NULL,
  HE25_NR_EQUIP INTEGER NOT NULL,
  HE25_HR_COLETA TIME NOT NULL,
  HE25_ST_DIAS VARCHAR(30) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252);

ALTER TABLE HE25 ADD PRIMARY KEY (HE25_AT_COD);


/* Structure for the `HE26` table :  */

CREATE TABLE HE26 (
  HE26_NR_FNCESPEC INTEGER DEFAULT 0 NOT NULL,
  HE26_NR_FUNC INTEGER DEFAULT 0 NOT NULL);



/* Structure for the `HE27` table :  */

CREATE TABLE HE27 (
  HE27_AT_COD INTEGER NOT NULL,
  HE27_ST_DESC VARCHAR(30) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE27_NR_INDEX SMALLINT DEFAULT 0 NOT NULL,
  HE27_NR_EQUIP INTEGER DEFAULT 0 NOT NULL,
  HE27_BL_CATRACA SMALLINT DEFAULT 0 NOT NULL,
  HE27_BL_WORKOFF SMALLINT DEFAULT 0 NOT NULL,
  HE27_ST_LEITORA1 VARCHAR(6) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE27_ST_LEITORA2 VARCHAR(6) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE27_NR_TMPRELE1 SMALLINT DEFAULT 0 NOT NULL,
  HE27_NR_TMPRELE2 SMALLINT DEFAULT 0 NOT NULL,
  HE27_NR_TMPRELE3 SMALLINT DEFAULT 0 NOT NULL,
  HE27_ST_SENSOR1 VARCHAR(50) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE27_ST_SENSOR2 VARCHAR(50) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE27_ST_SENSOR3 VARCHAR(50) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE27_ST_FACILITY VARCHAR(40) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252);


ALTER TABLE HE27 ADD PRIMARY KEY (HE27_AT_COD);



/* Structure for the `HE28` table :  */

CREATE TABLE HE28 (
  HE28_DT_DIA DATE NOT NULL);



/* Structure for the `HE29` table :  */

CREATE TABLE HE29 (
  HE29_AT_COD INTEGER NOT NULL,
  HE29_ST_PATHIMAGEM VARCHAR(150) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE29_NR_FUNCIONARIO INTEGER NOT NULL);



/* Structure for the `HE30` table :  */

CREATE TABLE HE30 (
  HE30_AT_COD INTEGER NOT NULL,
  HE30_ST_ADMINNAME VARCHAR(30) CHARACTER SET WIN1252 NOT NULL COLLATE PXW_INTL850,
  HE30_ST_LOGIN VARCHAR(20) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE30_ST_SENHA VARCHAR(20) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252,
  HE30_BL_CADADMIN SMALLINT DEFAULT 0 NOT NULL,
  HE30_BL_CADUSER SMALLINT DEFAULT 0 NOT NULL,
  HE30_BL_CADHOR SMALLINT DEFAULT 0 NOT NULL,
  HE30_BL_VIEWREPORT SMALLINT DEFAULT 0 NOT NULL,
  HE30_BL_LIBEXTRA SMALLINT DEFAULT 0 NOT NULL);


ALTER TABLE HE30 ADD PRIMARY KEY (HE30_AT_COD);



/* Structure for the `HE31` table :  */

CREATE TABLE HE31 (
  HE31_AT_COD SMALLINT NOT NULL,
  HE31_ST_DESCRICAO VARCHAR(20) CHARACTER SET WIN1252 DEFAULT '' NOT NULL COLLATE WIN1252);


ALTER TABLE HE31 ADD PRIMARY KEY (HE31_AT_COD);



/* Structure for the `HE32` table :  */

CREATE TABLE HE32 (
  HE32_NR_ROTA SMALLINT DEFAULT 0 NOT NULL,
  HE32_NR_EQUIP SMALLINT DEFAULT 0 NOT NULL,
  HE32_NR_ORDEM SMALLINT DEFAULT 0 NOT NULL);



/* Structure for the `HE33` table :  */

CREATE TABLE HE33 (
  HE33_AT_COD SMALLINT NOT NULL,
  HE33_NR_EQUIP SMALLINT DEFAULT 0 NOT NULL,
  HE33_NR_USERLIBEROU SMALLINT DEFAULT 0 NOT NULL,
  HE33_DT_LIBERACAO TIMESTAMP,
  HE33_NR_USUARIO SMALLINT DEFAULT 0 NOT NULL,
  HE33_DT_UTILIZACAO TIMESTAMP,
  HE33_BL_UTILIZADO SMALLINT DEFAULT 0 NOT NULL);


ALTER TABLE HE33 ADD PRIMARY KEY (HE33_AT_COD);



/* Structure for the `HE34` table :  */

CREATE TABLE HE34 (
  HE34_AT_COD SMALLINT NOT NULL,
  HE34_NR_VISITANTE SMALLINT DEFAULT 0 NOT NULL,
  HE34_NR_ROTA SMALLINT DEFAULT 0 NOT NULL,
  HE34_ST_MATRICULA VARCHAR(20) CHARACTER SET WIN1252 DEFAULT '',
  HE34_DT_ENTRADA TIMESTAMP,
  HE34_DT_SAIDA TIMESTAMP,
  HE34_NR_NIVEL_PREV SMALLINT DEFAULT -1 NOT NULL,
  HE34_NR_NIVEL_NEXT SMALLINT DEFAULT 0 NOT NULL
);


ALTER TABLE HE34 ADD PRIMARY KEY (HE34_AT_COD);


/* Structure for the `HE35` table :  */

CREATE TABLE HE35 (
  HE35_AT_COD SMALLINT NOT NULL,
  HE35_ST_NOME VARCHAR(100) CHARACTER SET WIN1252 DEFAULT '',
  HE35_ST_CPF VARCHAR(20) CHARACTER SET WIN1252 DEFAULT '',
  HE35_ST_RG VARCHAR(20) CHARACTER SET WIN1252 DEFAULT '',
  HE33_BN_OBS BLOB SUB_TYPE 2 NOT NULL);


ALTER TABLE HE35 ADD PRIMARY KEY (HE35_AT_COD);


/* Structure for the `HE36` table :  */

CREATE TABLE HE36 (
  HE36_AT_COD INTEGER NOT NULL,
  HE36_NR_EQUIP INTEGER NOT NULL,
  HE36_ST_MAT_INI VARCHAR(20) NOT NULL,
  HE36_ST_MAT_FIM VARCHAR(20) NOT NULL,
  HE36_FL_ACESSO INTEGER DEFAULT 0 NOT NULL,
  HE36_FL_TPUSER INTEGER DEFAULT 0 NOT NULL,
  HE36_NR_HORARIO INTEGER DEFAULT 0,
  HE36_ST_DESCHOR VARCHAR(30),
  HE36_BL_VERDIG INTEGER DEFAULT 1 NOT NULL,
  HE36_BL_BLOQUEIO SMALLINT DEFAULT 0 NOT NULL,
  HE36_DT_BLOQINI DATE,
  HE36_DT_BLOQEND DATE,
  HE36_ST_RELES VARCHAR(3) CHARACTER SET NONE DEFAULT '' NOT NULL COLLATE NONE,
  HE36_ST_CONTROLADORES VARCHAR(10) CHARACTER SET NONE DEFAULT '' NOT NULL COLLATE NONE,
  HE36_BL_LISTADO SMALLINT DEFAULT 1 NOT NULL
);


ALTER TABLE HE36 ADD PRIMARY KEY (HE36_AT_COD);


/* Structure for the `HE37` table :  */

CREATE TABLE HE37 (
  HE37_AT_COD INTEGER NOT NULL, 
  HE37_NR_USUARIO INTEGER NOT NULL, 
  HE37_ST_MATRICULA VARCHAR(20) CHARACTER SET NONE DEFAULT '''' NOT NULL COLLATE WIN1252
);


ALTER TABLE HE37 ADD PRIMARY KEY (HE37_AT_COD);


CREATE TABLE HE38 (
  HE38_NR_EQUIP INTEGER DEFAULT 0 NOT NULL,
	HE38_ST_CAMINHO VARCHAR(200) CHARACTER SET WIN1252 COLLATE PXW_INTL850,
	HE38_DT_ULTIMA_COLETA TIMESTAMP,
  HE38_BL_NOME_DINAMICO SMALLINT DEFAULT 1 NOT NULL
);

/* Structure for the `HE39 table :  */

CREATE TABLE HE39 (
  HE39_AT_COD INTEGER NOT NULL,
  HE39_NR_EQUIP INTEGER NOT NULL,
  HE39_HR_ENVIO TIME NOT NULL,
  HE39_ST_DIAS VARCHAR(30) CHARACTER SET NONE DEFAULT '' NOT NULL COLLATE NONE,
  HE39_NR_LAST_ID INTEGER DEFAULT -1 NOT NULL,
  HE39_NR_SEND INTEGER DEFAULT 0 NOT NULL,
  HE39_ST_FILE VARCHAR(255) CHARACTER SET NONE DEFAULT '' NOT NULL COLLATE NONE	
);

ALTER TABLE HE39 ADD PRIMARY KEY (HE39_AT_COD);

/* Structure for the `HE40 table :  */

CREATE TABLE HE40 (
	HE40_NR_ID INTEGER NOT NULL, 
	HE40_NR_NUM INTEGER NOT NULL
);

	
/* Definition for the `BI_HE00_HE00_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE00_HE00_AT_COD FOR HE00
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE00_AT_COD IS NULL) THEN
      NEW.HE00_AT_COD = GEN_ID(HE00_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE01_HE01_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE01_HE01_AT_COD FOR HE01
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN IF (NEW.HE01_AT_COD IS NULL) THEN NEW.HE01_AT_COD = GEN_ID(HE01_AT_COD_GEN, 1); END^

SET TERM ; ^

/* Definition for the `BI_HE02_HE02_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE02_HE02_AT_COD FOR HE02
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE02_AT_COD IS NULL) THEN
      NEW.HE02_AT_COD = GEN_ID(HE02_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE03_HE03_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE03_HE03_AT_COD FOR HE03
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE03_AT_COD IS NULL) THEN
      NEW.HE03_AT_COD = GEN_ID(HE03_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE04_HE04_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE04_HE04_AT_COD FOR HE04
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE04_AT_COD IS NULL) THEN
      NEW.HE04_AT_COD = GEN_ID(HE04_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE05_HE05_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE05_HE05_AT_COD FOR HE05
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE05_AT_COD IS NULL) THEN
      NEW.HE05_AT_COD = GEN_ID(HE05_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE06_HE06_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE06_HE06_AT_COD FOR HE06
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE06_AT_COD IS NULL) THEN
      NEW.HE06_AT_COD = GEN_ID(HE06_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE07_HE07_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE07_HE07_AT_COD FOR HE07
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN NEW.HE07_AT_COD = GEN_ID(HE07_AT_COD_GEN, 1); END^

SET TERM ; ^

/* Definition for the `BI_HE08_HE08_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE08_HE08_AT_COD FOR HE08
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN NEW.HE08_AT_COD = GEN_ID(HE08_AT_COD_GEN, 1); END^

SET TERM ; ^

/* Definition for the `BI_HE09_HE09_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE09_HE09_AT_COD FOR HE09
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE09_AT_COD IS NULL) THEN
      NEW.HE09_AT_COD = GEN_ID(HE09_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE10_HE10_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE10_HE10_AT_COD FOR HE10
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE10_AT_COD IS NULL) THEN
      NEW.HE10_AT_COD = GEN_ID(HE10_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE11_HE11_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE11_HE11_AT_COD FOR HE11
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE11_AT_COD IS NULL) THEN
      NEW.HE11_AT_COD = GEN_ID(HE11_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE12_HE12_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE12_HE12_AT_COD FOR HE12
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE12_AT_COD IS NULL) THEN
      NEW.HE12_AT_COD = GEN_ID(HE12_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE13_HE13_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE13_HE13_AT_COD FOR HE13
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE13_AT_COD IS NULL) THEN
      NEW.HE13_AT_COD = GEN_ID(HE13_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE14_HE14_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE14_HE14_AT_COD FOR HE14
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE14_AT_COD IS NULL) THEN
      NEW.HE14_AT_COD = GEN_ID(HE14_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE14_HE14_NR_EQUIP` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE14_HE14_NR_EQUIP FOR HE14
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE14_NR_EQUIP IS NULL) THEN
      NEW.HE14_NR_EQUIP = GEN_ID(HE14_NR_EQUIP_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE15_HE15_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE15_HE15_AT_COD FOR HE15
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE15_AT_COD IS NULL) THEN
      NEW.HE15_AT_COD = GEN_ID(HE15_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE16_HE16_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE16_HE16_AT_COD FOR HE16
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE16_AT_COD IS NULL) THEN
      NEW.HE16_AT_COD = GEN_ID(HE16_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE17_HE17_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE17_HE17_AT_COD FOR HE17
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE17_AT_COD IS NULL) THEN
      NEW.HE17_AT_COD = GEN_ID(HE17_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE18_HE18_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE18_HE18_AT_COD FOR HE18
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE18_AT_COD IS NULL) THEN
      NEW.HE18_AT_COD = GEN_ID(HE18_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE19_HE19_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE19_HE19_AT_COD FOR HE19
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE19_AT_COD IS NULL) THEN
      NEW.HE19_AT_COD = GEN_ID(HE19_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE20_HE20_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE20_HE20_AT_COD FOR HE20
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE20_AT_COD IS NULL) THEN
      NEW.HE20_AT_COD = GEN_ID(HE20_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE21_HE21_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE21_HE21_AT_COD FOR HE21
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE21_AT_COD IS NULL) THEN
      NEW.HE21_AT_COD = GEN_ID(HE21_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE22_HE22_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE22_HE22_AT_COD FOR HE22
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE22_AT_COD IS NULL) THEN
      NEW.HE22_AT_COD = GEN_ID(HE22_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE23_HE23_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE23_HE23_AT_COD FOR HE23
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE23_AT_COD IS NULL) THEN
      NEW.HE23_AT_COD = GEN_ID(HE23_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE25_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE25_HE25_AT_COD FOR HE25
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE25_AT_COD IS NULL) THEN
      NEW.HE25_AT_COD = GEN_ID(HE25_AT_COD_GEN, 1);
END^

SET TERM ; ^


/* Definition for the `BI_HE30_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE30_AT_COD FOR HE30
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE30_AT_COD IS NULL) THEN
      NEW.HE30_AT_COD = GEN_ID(HE30_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE31_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE31_AT_COD FOR HE31
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE31_AT_COD IS NULL) THEN
      NEW.HE31_AT_COD = GEN_ID(HE31_AT_COD_GEN, 1);
END^

SET TERM ; ^

/* Definition for the `BI_HE33_HE33_AT_COD` trigger :  */

SET TERM ^ ;

CREATE TRIGGER BI_HE33_HE33_AT_COD FOR HE33
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE33_AT_COD IS NULL) THEN
      NEW.HE33_AT_COD = GEN_ID(HE33_AT_COD_GEN, 1);
END^

SET TERM ; ^

SET TERM ^ ;

CREATE TRIGGER BI_HE34_HE34_AT_COD FOR HE34
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE34_AT_COD IS NULL) THEN
      NEW.HE34_AT_COD = GEN_ID(HE34_AT_COD_GEN, 1);
END^

SET TERM ; ^

SET TERM ^ ;

CREATE TRIGGER BI_HE35_HE35_AT_COD FOR HE35
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE35_AT_COD IS NULL) THEN
      NEW.HE35_AT_COD = GEN_ID(HE35_AT_COD_GEN, 1);
END^

SET TERM ; ^


SET TERM ^;

CREATE TRIGGER BI_HE36_HE36_AT_COD FOR HE36
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.HE36_AT_COD IS NULL) THEN
		NEW.HE36_AT_COD = GEN_ID(HE36_AT_COD_GEN, 1);
END^

SET TERM ;^


SET TERM ^;

CREATE TRIGGER BI_HE37_HE37_AT_COD FOR HE37
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
	IF (NEW.HE37_AT_COD IS NULL) THEN
		NEW.HE37_AT_COD = GEN_ID(HE37_AT_COD_GEN, 1);
END;

SET TERM ; ^

SET TERM ^;

CREATE TRIGGER BI_HE39_HE39_AT_COD FOR HE39
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN 
	IF (NEW.HE39_AT_COD IS NULL) THEN 
		NEW.HE39_AT_COD = GEN_ID(HE39_AT_COD_GEN, 1);
END^
	
SET TERM ; ^

INSERT INTO HE00 (HE00_NR_VERSAO) VALUES (7077);
