param([string]$ConfigPath = "$PSScriptRoot\agent.env")
$ErrorActionPreference="Stop"
function Log([string]$Text,[string]$Level="INFO"){$dir=Join-Path $PSScriptRoot "logs";New-Item -ItemType Directory -Force $dir|Out-Null;Add-Content (Join-Path $dir "offline-release.log") "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss.fff') [$Level] $Text" -Encoding UTF8}
function Env([string]$Path){$map=@{};Get-Content $Path -Encoding UTF8|ForEach-Object{$line=$_.Trim();if($line -and -not $line.StartsWith("#")){$p=$line.Split("=",2);if($p.Count-eq 2){$map[$p[0].Trim()]=$p[1].Trim()}}};$map}
function Hex([string]$Value){$clean=$Value-replace'[^0-9A-Fa-f]','';$bytes=New-Object byte[] ($clean.Length/2);for($i=0;$i-lt$bytes.Length;$i++){$bytes[$i]=[Convert]::ToByte($clean.Substring($i*2,2),16)};$bytes}
function Response($stream){$all=New-Object System.Collections.Generic.List[byte];$buf=New-Object byte[] 1024;$start=Get-Date;$last=Get-Date;while(((Get-Date)-$start).TotalMilliseconds-lt3000){if($stream.DataAvailable){$n=$stream.Read($buf,0,$buf.Length);for($i=0;$i-lt$n;$i++){$all.Add($buf[$i])};$last=Get-Date}elseif($all.Count-gt0-and((Get-Date)-$last).TotalMilliseconds-ge130){break}else{Start-Sleep -Milliseconds 20}};(($all|ForEach-Object{$_.ToString("X2")})-join"")}
function Henry([string]$HostName,[int]$Port){$c=New-Object Net.Sockets.TcpClient;$task=$c.ConnectAsync($HostName,$Port);if(-not$task.Wait(3000)){$c.Dispose();throw"Timeout na catraca"};try{$s=$c.GetStream();$a=Hex"FE8A7100010100050000";$s.Write($a,0,$a.Length);$s.Flush();$r1=Response $s;Start-Sleep -Milliseconds 350;$b=Hex"FE8671000201000A030506";$s.Write($b,0,$b.Length);$s.Flush();$r2=Response $s;if($r1-ne"018A7100010000FB"-or$r2-ne"01867100020000F4"){throw"Catraca nao confirmou a liberacao"}}finally{$c.Close();$c.Dispose()}}
$cfg=Env $ConfigPath;$hostName=[string]$cfg["ACCESS_HOST"];$port=[int]$cfg["ACCESS_PORT"];$driver=([string]$cfg["ACCESS_DRIVER"]).ToLower();$data=Join-Path $PSScriptRoot "data";New-Item -ItemType Directory -Force $data|Out-Null;Log "Executor local iniciado. Driver=$driver"
while($true){$queue=Join-Path $data "local-release.jsonl";$work=Join-Path $data "local-release.processing";if(Test-Path $queue){try{Move-Item -Force $queue $work}catch{};if(Test-Path $work){try{Get-Content $work -Encoding UTF8|ForEach-Object{if($_.Trim()){try{$item=$_|ConvertFrom-Json;if($driver-eq"henry7x"){Henry $hostName $port}elseif($driver-eq"simulador"){Start-Sleep -Milliseconds 100}else{throw"Driver offline ainda nao habilitado: $driver"};Log "Liberacao concluida: $($item.id) $($item.pessoaNome)"}catch{Log $_.Exception.Message "ERROR"}}}}finally{Remove-Item -Force $work -ErrorAction SilentlyContinue}}};Start-Sleep -Milliseconds 150}
