package com.fusionerp.terminal;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.util.Base64;import android.view.*;import android.widget.*;
import androidx.activity.result.ActivityResultLauncher;import androidx.activity.result.contract.ActivityResultContracts;import androidx.appcompat.app.AppCompatActivity;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.view.PreviewView;import androidx.core.content.ContextCompat;
import com.google.common.util.concurrent.ListenableFuture;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;

public class MainActivity extends AppCompatActivity {
  private PreviewView preview;private TextView title,message,status;private LinearLayout setup;private EditText host,code;private ImageCapture capture;private final ScheduledExecutorService scheduler=Executors.newSingleThreadScheduledExecutor();private ExecutorService cameraExecutor;private volatile boolean busy=false;private int failures=0;private long lockedUntil=0;private String baseUrl,token;
  private final ActivityResultLauncher<String> permission=registerForActivityResult(new ActivityResultContracts.RequestPermission(),ok->{if(ok)startCamera();else show("Câmera necessária","Autorize a câmera nas configurações.",true);});
  @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);setContentView(com.fusionerp.terminal.R.layout.activity_main);preview=findViewById(R.id.preview);title=findViewById(R.id.title);message=findViewById(R.id.message);status=findViewById(R.id.status);setup=findViewById(R.id.setup);host=findViewById(R.id.host);code=findViewById(R.id.code);cameraExecutor=Executors.newSingleThreadExecutor();SharedPreferences p=getSharedPreferences("fusion",MODE_PRIVATE);baseUrl=p.getString("base","");token=p.getString("token","");findViewById(R.id.connect).setOnClickListener(v->pair());if(!token.isEmpty()){setup.setVisibility(View.GONE);requestCamera();}else show("Configurar terminal","Veja o IP e o código em Status do Fusion Access no computador.",false);}
  private void requestCamera(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)startCamera();else permission.launch(Manifest.permission.CAMERA);}
  private void startCamera(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider provider=f.get();Preview pv=new Preview.Builder().build();pv.setSurfaceProvider(preview.getSurfaceProvider());capture=new ImageCapture.Builder().setCaptureMode(ImageCapture.CAPTURE_MODE_MINIMIZE_LATENCY).setJpegQuality(82).build();provider.unbindAll();provider.bindToLifecycle(this,CameraSelector.DEFAULT_FRONT_CAMERA,pv,capture);show("Posicione seu rosto","Reconhecimento local pronto.",false);scheduler.scheduleWithFixedDelay(this::cycle,1500,1800,TimeUnit.MILLISECONDS);}catch(Exception e){show("Falha na câmera",e.getMessage(),true);}},ContextCompat.getMainExecutor(this));}
  private void pair(){String ip=host.getText().toString().trim().replace("http://","");String pair=code.getText().toString().trim();if(ip.isEmpty()||pair.length()!=6){show("Dados incompletos","Informe o IP e o código de seis números.",true);return;}baseUrl="http://"+ip+":8765";Executors.newSingleThreadExecutor().execute(()->{try{JSONObject result=request("/pair",new JSONObject(),null,pair);token=result.getString("token");getSharedPreferences("fusion",MODE_PRIVATE).edit().putString("base",baseUrl).putString("token",token).apply();runOnUiThread(()->{setup.setVisibility(View.GONE);requestCamera();});}catch(Exception e){show("Não foi possível conectar",e.getMessage(),true);}});}
  private void cycle(){if(busy||capture==null)return;if(System.currentTimeMillis()<lockedUntil){long s=Math.max(1,(lockedUntil-System.currentTimeMillis()+999)/1000);show("Aguarde", "Nova tentativa em "+s+" segundos.",true);return;}busy=true;try{File photo=File.createTempFile("fusion-face-",".jpg",getCacheDir());ImageCapture.OutputFileOptions options=new ImageCapture.OutputFileOptions.Builder(photo).build();capture.takePicture(options,cameraExecutor,new ImageCapture.OnImageSavedCallback(){public void onImageSaved(ImageCapture.OutputFileResults r){try{byte[] bytes=read(photo);photo.delete();JSONObject body=new JSONObject().put("imagem",Base64.encodeToString(bytes,Base64.NO_WRAP)).put("terminalId",Build.MODEL);JSONObject result=request("/identify",body,token,null);boolean recognized=result.optBoolean("reconhecido"),authorized=result.optBoolean("autorizado");if(recognized)failures=0;else if(++failures>=3){failures=0;lockedUntil=System.currentTimeMillis()+30000;}if(authorized)show("Acesso liberado",result.optJSONObject("pessoa").optString("nome","Bem-vindo"),false);else show(recognized?"Acesso não liberado":"Rosto não reconhecido",result.optString("motivo")+(recognized?"":" · Restam "+(3-failures)+" tentativa(s)"),true);}catch(Exception e){show("Modo local indisponível",e.getMessage(),true);}finally{busy=false;}}public void onError(ImageCaptureException e){busy=false;show("Falha na captura",e.getMessage(),true);}});}catch(Exception e){busy=false;show("Falha na captura",e.getMessage(),true);}}
  private JSONObject request(String path,JSONObject body,String auth,String pair)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(baseUrl+path).openConnection();c.setConnectTimeout(2500);c.setReadTimeout(12000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");if(auth!=null)c.setRequestProperty("X-Fusion-Local-Token",auth);if(pair!=null)c.setRequestProperty("X-Fusion-Pair-Code",pair);try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();String text=new String(read(in),StandardCharsets.UTF_8);JSONObject result=new JSONObject(text);if(!result.optBoolean("ok"))throw new IOException(result.optString("mensagem","Falha no terminal local"));return result;}
  private static byte[] read(File file)throws IOException{try(InputStream in=new FileInputStream(file)){return read(in);}}private static byte[] read(InputStream in)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];for(int n;(n=in.read(b))>0;)out.write(b,0,n);return out.toByteArray();}
  private void show(String a,String b,boolean error){runOnUiThread(()->{title.setText(a);message.setText(b);status.setText(token==null||token.isEmpty()?"Aguardando pareamento":"Conexão direta com o computador");status.setBackgroundColor(Color.parseColor(error?"#CC641F2A":"#CC073A29"));});}
  @Override protected void onDestroy(){super.onDestroy();scheduler.shutdownNow();cameraExecutor.shutdownNow();}
}
